#!/bin/bash

if [ -z "${hisitopdir}" ]; then export hisitopdir=$(hisitopdir.sh $0); fi
. ${hisitopdir}/autelan_scripts/make.in

#
#$1:version
#
main() {
        local version=$1

	make_obj ${version} no_install md
}

main "$@"

